services:
  postgres:
    image: postgres:16-alpine
    container_name: job_finder_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: job_finder
      POSTGRES_PASSWORD: job_finder
      POSTGRES_DB: job_finder
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
